[theme]
primaryColor = "#764ba2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
port = 8502
enableCORS = false

[browser]
gatherUsageStats = false
